import dr_patel from "../../public/dr_patel.jpg";
import dr_Njeri from "../../public/dr_patel.jpg";
const table = [
  {
    morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sinh",
    },
    mid_morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "1000hrs-1300hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    evening: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "1300hrs-1600hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
  },
  {
    morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    mid_morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    evening: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
  },
  {
    morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_patel,
      lec: "Dr.Patel Sighn",
    },
    mid_morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 103",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    evening: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "Free Lesson",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
  },
  {
    morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    mid_morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    evening: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
  },
  {
    morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    mid_morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    evening: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
  },
  {
    morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    mid_morning: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
    evening: {
      date_name: "Mon",
      date_number: "27/3/2023",
      unit: "AMM 102",
      time: "0700hrs-1000hrs",
      venue: "Tution Block",
      img: dr_Njeri,
      lec: "Dr.Patel Sighn",
    },
  },
];
export default table;
