import dr_patel from "../../../public/dr_patel.jpg";
import dr_Njeri from "../../../public/dr_Njeri.jpg";
import lec1 from "../../../public/lec1.webp";
import lec2 from "../../../public/lec2.webp";
import lec3 from "../../../public/lec3.webp";
import lec4 from "../../../public/lec4.webp";

const Bsc_IT = [
  {
    Y1S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "BCE 101",
          time: "1300hrs-1600hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Nyagisera",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "UCU 102",
          time: "1000hrs-1300hrs",
          venue: "Online",
          img: lec1,
          lec: "Sarah",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "SIT 104",
          time: "1300hrs-1600hrs",
          venue: "F2.2",
          img: lec2,
          lec: "Juliet",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "BCE 101",
          time: "1300hrs-1600hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Nyagisera",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "Agina",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SIT 103",
          time: "0700hrs-1000hrs",
          venue: "F3 Lab",
          img: lec1,
          lec: "J.Kimiri",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "SIT 105",
          time: "1000hrs-1300hrs",
          venue: "F4 Lab",
          img: lec1,
          lec: "G. Muturi",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y2S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "SIT 203",
          time: "0700hrs-1000hrs",
          venue: "F3.3",
          img: lec3,
          lec: "P.Kimemiah",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "BCA 211/BCA 200",
          time: "0700hrs-1000hrs",
          venue: "F4.1,F4.2",
          img: lec1,
          lec: "Dr. R. Mwende",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "EET 215",
          time: "1000hrs-1300hrs",
          venue: "DH4A",
          img: lec1,
          lec: "Gordon",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "SIT 204",
          time: "1300hrs-1600hrs",
          venue: "G4 Lab",
          img: lec2,
          lec: "Dr. G. Mariga",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "SIT 202",
          time: "0700hrs-1000hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Dr. R. Ndung'u",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SCS 205",
          time: "1000hrs-1300hrs",
          venue: "DH3A",
          img: lec1,
          lec: "Knight",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "SCS 203",
          time: "1300hrs-1600hrs",
          venue: "MLH2",
          img: lec2,
          lec: "Mutembei",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y3S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "SCS 301",
          time: "1600hrs-1900hrs",
          venue: "GF2",
          img: dr_Njeri,
          lec: "Nekesa",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "SIT 304",
          time: "0700hrs-1000hrs",
          venue: "GF4 Lab",
          img: dr_Njeri,
          lec: "Juliet",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SCS 302",
          time: "0700hrs-1000hrs",
          venue: "GF3",
          img: lec1,
          lec: "S.Karanja",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SCS 303",
          time: "1300hrs-1600hrs",
          venue: "GF3",
          img: lec2,
          lec: "Knight",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SIT 306",
          time: "1600hrs-1900hrs",
          venue: "F1.2",
          img: lec4,
          lec: "Agina",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "SCIT 305",
          time: "0700hrs-1000hrs",
          venue: "F2.2",
          img: lec1,
          lec: "C.Kiarie",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y4S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec3,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "SCS 422",
          time: "1000hrs-1300hrs",
          venue: "GF4",
          img: lec4,
          lec: "Dr. G. Mariga",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc IT",
          unit: "SIT 408",
          time: "1300hrs-1600hrs",
          venue: "DH3B",
          img: lec2,
          lec: "S.Kigotho",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc IT",
          unit: "SIT 406",
          time: "1600hrs-1900hrs",
          venue: "F2.4",
          img: dr_Njeri,
          lec: "Agina",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None"
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SCS 414",
          time: "0700hrs-1000hrs",
          venue: "F3.1",
          img: lec1,
          lec: "Knight",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SIT 405",
          time: "1000hrs-1300hrs",
          venue: "F3.3",
          img: lec1,
          lec: "P.Bitok",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "SIT 405",
          time: "1300hrs-1600hrs",
          venue: "F3.3",
          img: lec2,
          lec: "Dr. J. Njuki",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    }
  }
]
const BBIT = [
  {
    Y1S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "SIT 102",
          time: "1000hrs-1300hrs",
          venue: "F3.2",
          img: dr_patel,
          lec: "P.Kimemia",
        },
        evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "BCE 101",
          time: "1300hrs-1600hrs",
          venue: "F3.2",
          img: dr_Njeri,
          lec: "Nyagisera",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "SIT 404",
          time: "0700hrs-1000hrs",
          venue: "MLH1",
          img: lec2,
          lec: "Juliet",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "UCU 102",
          time: "1000hrs-1300hrs",
          venue: "Online",
          img: lec1,
          lec: "Sarah",
        },
        evening: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "UCU 103",
          time: "1300hrs-1600hrs",
          venue: "Online",
          img: dr_Njeri,
          lec: "Dr. R. Mburu",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "Agina",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "SIT 103",
          time: "1000hrs-1300hrs",
          venue: "F3 Lab",
          img: lec1,
          lec: "J.Kimiri",
        },
        evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "BCM 200",
          time: "1300hrs-1600hrs",
          venue: "F3.4",
          img: lec2,
          lec: "Irene",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y2S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec3,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "BCA 211/BCA 200",
          time: "0700hrs-1000hrs",
          venue: "F4.1,F4.2",
          img: lec1,
          lec: "Dr. R. Mwende",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "BHR 100",
          time: "1000hrs-1300hrs",
          venue: "F1.3",
          img: lec1,
          lec: "Syombua",
        },
        evening: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "SIT 204",
          time: "0700hrs-1000hrs",
          venue: "F3 Lab",
          img: dr_Njeri,
          lec: "Dr. R. Ndung'u",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc IT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y3S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "SIT 304",
          time: "1000hrs-1300hrs",
          venue: "G4 Lab",
          img: lec1,
          lec: "J.Kimiri",
        },
        evening: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec3,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "AMS 319",
          time: "1000hrs-1300hrs",
          venue: "F2.1",
          img: lec1,
          lec: "H. Kibunja",
        },
        evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "BCF 200",
          time: "0700hrs-1000hrs",
          venue: "F1.1",
          img: lec1,
          lec: "Momanyi",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "SIT 305",
          time: "1000hrs-1300hrs",
          venue: "F3.2",
          img: lec1,
          lec: "C.Kiarie",
        },
        evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y4S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec3,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "SIT 405",
          time: "1300hrs-1600hrs",
          venue: "F1.2",
          img: dr_patel,
          lec: "W.Lacktano",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Tue",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BBIT",
          unit: "SIT 406",
          time: "1600hrs-1900hrs",
          venue: "F2.4",
          img: dr_patel,
          lec: "Agina",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "SIT 407",
          time: "0700hrs-1000hrs",
          venue: "F1.3",
          img: dr_patel,
          lec: "Agina",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BBIT",
          unit: "SCS 422",
          time: "1000hrs-1300hrs",
          venue: "F1.3",
          img: dr_Njeri,
          lec: "Dr.J.Ndia",
        },
        evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None"
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None"
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None"
        },
        evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "BHR 303",
          time: "1300hrs-1600hrs",
          venue: "F1.4",
          img: lec2,
          lec: "Dr. T. Karanja",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BBIT",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    }
  }
]

const Bsc_SE = [
  {
    Y1S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "SCS 103",
          time: "0700hrs-1000hrs",
          venue: "Assembly Hall",
          img: lec1,
          lec: "Millicent",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "UCU 102",
          time: "1000hrs-1300hrs",
          venue: "Online",
          img: lec1,
          lec: "Sarah",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "UCU 103",
          time: "1300hrs-1600hrs",
          venue: "Online",
          img: dr_Njeri,
          lec: "Dr. R. Mburu",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SIT 103",
          time: "0700hrs-1000hrs",
          venue: "F3 Lab",
          img: lec1,
          lec: "J.Kimiri",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "SIT 105",
          time: "1000hrs-1300hrs",
          venue: "F4 Lab",
          img: lec1,
          lec: "G. Muturi",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y2S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "SIT 203",
          time: "0700hrs-1000hrs",
          venue: "F3.3",
          img: lec3,
          lec: "P.Kimemiah",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "BCA 211/BCA 200",
          time: "0700hrs-1000hrs",
          venue: "F4.1,F4.2",
          img: lec1,
          lec: "Dr. R. Mwende",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "EET 215",
          time: "1000hrs-1300hrs",
          venue: "DH4A",
          img: lec1,
          lec: "Gordon",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "SIT 204",
          time: "1300hrs-1600hrs",
          venue: "G4 Lab",
          img: lec2,
          lec: "Dr. G. Mariga",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "SIT 202",
          time: "0700hrs-1000hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Dr. R. Ndung'u",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SCS 205",
          time: "1000hrs-1300hrs",
          venue: "DH3A",
          img: lec1,
          lec: "Knight",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "SCS 203",
          time: "1300hrs-1600hrs",
          venue: "MLH2",
          img: lec2,
          lec: "Mutembei",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y3S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "SCS 301",
          time: "1600hrs-1900hrs",
          venue: "GF2",
          img: dr_Njeri,
          lec: "Nekesa",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "SIT 304",
          time: "0700hrs-1000hrs",
          venue: "GF4 Lab",
          img: dr_Njeri,
          lec: "Juliet",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SCS 302",
          time: "0700hrs-1000hrs",
          venue: "GF3",
          img: lec1,
          lec: "S.Karanja",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SCS 303",
          time: "1300hrs-1600hrs",
          venue: "GF3",
          img: lec2,
          lec: "Knight",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SIT 306",
          time: "1600hrs-1900hrs",
          venue: "F1.2",
          img: lec4,
          lec: "Agina",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "SCIT 305",
          time: "0700hrs-1000hrs",
          venue: "F2.2",
          img: lec1,
          lec: "C.Kiarie",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y4S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec3,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "SCS 422",
          time: "1000hrs-1300hrs",
          venue: "GF4",
          img: lec4,
          lec: "Dr. G. Mariga",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc SE",
          unit: "SIT 408",
          time: "1300hrs-1600hrs",
          venue: "DH3B",
          img: lec2,
          lec: "S.Kigotho",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc SE",
          unit: "SIT 406",
          time: "1600hrs-1900hrs",
          venue: "F2.4",
          img: dr_Njeri,
          lec: "Agina",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None"
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SCS 414",
          time: "0700hrs-1000hrs",
          venue: "F3.1",
          img: lec1,
          lec: "Knight",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SIT 405",
          time: "1000hrs-1300hrs",
          venue: "F3.3",
          img: lec1,
          lec: "P.Bitok",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "SIT 405",
          time: "1300hrs-1600hrs",
          venue: "F3.3",
          img: lec2,
          lec: "Dr. J. Njuki",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc SE",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    }
  }
]



const Bsc_CS = [
  {
    Y1S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "BCE 101",
          time: "1300hrs-1600hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Nyagisera",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "UCU 102",
          time: "1000hrs-1300hrs",
          venue: "Online",
          img: lec1,
          lec: "Sarah",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "SIT 104",
          time: "1300hrs-1600hrs",
          venue: "F2.2",
          img: lec2,
          lec: "Juliet",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "BCE 101",
          time: "1300hrs-1600hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Nyagisera",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "Agina",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SIT 103",
          time: "0700hrs-1000hrs",
          venue: "F3 Lab",
          img: lec1,
          lec: "J.Kimiri",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "SIT 105",
          time: "1000hrs-1300hrs",
          venue: "F4 Lab",
          img: lec1,
          lec: "G. Muturi",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y2S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "SIT 203",
          time: "0700hrs-1000hrs",
          venue: "F3.3",
          img: lec3,
          lec: "P.Kimemiah",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "BCA 211/BCA 200",
          time: "0700hrs-1000hrs",
          venue: "F4.1,F4.2",
          img: lec1,
          lec: "Dr. R. Mwende",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "EET 215",
          time: "1000hrs-1300hrs",
          venue: "DH4A",
          img: lec1,
          lec: "Gordon",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "SIT 204",
          time: "1300hrs-1600hrs",
          venue: "G4 Lab",
          img: lec2,
          lec: "Dr. G. Mariga",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "SIT 202",
          time: "0700hrs-1000hrs",
          venue: "F3.1",
          img: dr_Njeri,
          lec: "Dr. R. Ndung'u",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SCS 205",
          time: "1000hrs-1300hrs",
          venue: "DH3A",
          img: lec1,
          lec: "Knight",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "SCS 203",
          time: "1300hrs-1600hrs",
          venue: "MLH2",
          img: lec2,
          lec: "Mutembei",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y3S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "SCS 301",
          time: "1600hrs-1900hrs",
          venue: "GF2",
          img: dr_Njeri,
          lec: "Nekesa",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "SIT 304",
          time: "0700hrs-1000hrs",
          venue: "GF4 Lab",
          img: dr_Njeri,
          lec: "Juliet",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SCS 302",
          time: "0700hrs-1000hrs",
          venue: "GF3",
          img: lec1,
          lec: "S.Karanja",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SCS 303",
          time: "1300hrs-1600hrs",
          venue: "GF3",
          img: lec2,
          lec: "Knight",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SIT 306",
          time: "1600hrs-1900hrs",
          venue: "F1.2",
          img: lec4,
          lec: "Agina",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "SCIT 305",
          time: "0700hrs-1000hrs",
          venue: "F2.2",
          img: lec1,
          lec: "C.Kiarie",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    },
    Y4S2: {
      Mon: {
        morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec3,
          lec: "None",
        },
        evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
      },
      Tue: {
        morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "SCS 422",
          time: "1000hrs-1300hrs",
          venue: "GF4",
          img: lec4,
          lec: "Dr. G. Mariga",
        },
        evening: {
          date_name: "Tue",
          course_name: "BSc CS",
          unit: "SIT 408",
          time: "1300hrs-1600hrs",
          venue: "DH3B",
          img: lec2,
          lec: "S.Kigotho",
        },
        late_evening: {
          date_name: "Mon",
          course_name: "BSc CS",
          unit: "SIT 406",
          time: "1600hrs-1900hrs",
          venue: "F2.4",
          img: dr_Njeri,
          lec: "Agina",
        },
      },
      Wed: {
        morning: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        mid_morning: {
          date_name: "wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: dr_Njeri,
          lec: "None",
        },
        evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Wed",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None"
        },
      },
      Thur: {
        morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SCS 414",
          time: "0700hrs-1000hrs",
          venue: "F3.1",
          img: lec1,
          lec: "Knight",
        },
        mid_morning: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SIT 405",
          time: "1000hrs-1300hrs",
          venue: "F3.3",
          img: lec1,
          lec: "P.Bitok",
        },
        evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "SIT 405",
          time: "1300hrs-1600hrs",
          venue: "F3.3",
          img: lec2,
          lec: "Dr. J. Njuki",
        },
        late_evening: {
          date_name: "Thur",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
      Fri: {
        morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "0700hrs-1000hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        mid_morning: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1000hrs-1300hrs",
          venue: "No Venue",
          img: lec1,
          lec: "None",
        },
        evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1300hrs-1600hrs",
          venue: "No Venue",
          img: lec2,
          lec: "None",
        },
        late_evening: {
          date_name: "Fri",
          course_name: "BSc CS",
          unit: "No Unit",
          time: "1600hrs-1900hrs",
          venue: "No Venue",
          img: lec4,
          lec: "None",
        },
      },
    }
  }
]



export default { Bsc_IT, Bsc_SE, BBIT, Bsc_CS};
